version: "3"
services:
  mongodb:
    image: mongo
    restart: always # 멈췄을 때 재실행 범위
    ports:
      - "27017:27017" # "" 생략 가능
    container_name: mongodb # 실행시킬 컨테이너 이름
    volumes:
      - ~/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb

networks: # 네트워크 설정, mongodb와 mongo-express가 엮이기(서로 통신하기) 위해 필요
  default:
    external:
      name: mongo_network
    